#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Octobox
# Runs the NGinx daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

# Wait for Octobox to become available
s6-svwait -u -t 5000 /var/run/s6/services/octobox

hass.log.info "Starting NGinx..."
exec nginx -g "daemon off;"
